# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
      - run: npm config set MONGODB_URL ${MONGODB_URL}
          npm config set PORT ${PORT}
          npm config set ENVNAME ${ENVNAME}
          npm i
        env:
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          PORT: ${{secrets.PORT}}
          ENVNAME: ${{secrets.ENVNAME}}
          CI: true
      - run: npm run build --if-present

      - name: Test
      - run: npm config set MONGODB_URL ${MONGODB_URL}
          npm config set PORT ${PORT}
          npm config set ENVNAME ${ENVNAME}
          npm test
        env:
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          PORT: ${{secrets.PORT}}
          ENVNAME: ${{secrets.ENVNAME}}
          CI: true
